version: '3.8'

services:
  db:
    container_name: postgresql-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=book-service-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
