spring:
  config:
    import: optional:file:.env[.properties]
  # Service DB connection configuration
  r2dbc:
    url: r2dbc:postgres://${POSTGRES_DB_URL:localhost:5432/book-service-db}
    username: ${POSTGRES_DB_USERNAME:user}
    password: ${POSTGRES_DB_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: none
  # Flyway DB connection configuration
  # Flyway is not supporting r2dbc yet
  flyway:
    url: jdbc:postgresql://${POSTGRES_DB_URL:localhost:5432/book-service-db}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    create-schemas: true
